Repository team-yuml-kkks/YumlJira, pull requests merged in 2019-09, with the labels that each got.

#22 #11 Add Bulma css framework and prepare scss file
  package-lock.json
  package.json
  yumljira/assets/app.js
  yumljira/assets/styles/custom.scss
  yumljira/assets/styles/index.scss
  yumljira/assets/styles/main.scss
  yumljira/assets/styles/variables.scss
Labels: enhancement

#15 #3 Setup vue testing environment with basic test files
  package-lock.json
  package.json
  tests/Name.spec.js
  tests/setup.js
  webpack/webpack.base.js
  yumljira/templates/Name.vue
Labels: enhancement

#25 Add avatar to user model #5
  README.md
  requirements/base.txt
  yumljira/apps/users/.tests.py.swp
  yumljira/apps/users/.utils.py.swp
  yumljira/apps/users/migrations/0002_user_avatar.py
  yumljira/apps/users/models.py
  yumljira/apps/users/serializers.py
  yumljira/apps/users/test_factories.py
  yumljira/apps/users/tests.py
  yumljira/apps/users/utils.py
  yumljira/assets/images/default_avatar.png
  yumljira/settings/auth.py
  yumljira/settings/base.py
Labels: enhancement

#26 Change ui docs template
  requirements/base.txt
  yumljira/settings/auth.py
  yumljira/settings/base.py
  yumljira/templates/redocs.html
  yumljira/templates/swagger-ui.html
  yumljira/urls.py
Labels: documentation

#27 Feature/vue router
  client/App.vue
  client/app.js
  client/components/.gitkeep
  client/fonts/.gitkeep
  client/router.js
  client/scripts/.gitkeep
  client/store/actions.js
  client/store/getters.js
  client/store/index.js
  client/store/mutations.js
  client/store/state.js
  client/styles/custom.scss
  client/styles/index.scss
  client/styles/variables.scss
  client/views/.gitkeep
  package-lock.json
  package.json
  tests/Name.spec.js
  tests/views/App.spec.js
  webpack/paths.js
  webpack/webpack.base.js
  yumljira/assets/app.js
  yumljira/assets/vendor/bootstrap.js
  yumljira/assets/vendor/bootstrap.scss
  yumljira/templates/base.html
Labels: enhancement

#37 Add avatar to user admin #13
  yumljira/apps/users/admin.py
Labels: enhancement

#31 Add tests for update and delete methods #29
  yumljira/apps/projects/tests.py
Labels: tests

#39 Add TimeLog model #34
  yumljira/apps/projects/migrations/0003_timelog.py
  yumljira/apps/projects/models.py
  yumljira/apps/projects/serializers.py
  yumljira/apps/projects/test_factories.py
  yumljira/apps/projects/tests.py
  yumljira/apps/projects/urls.py
  yumljira/apps/projects/views.py
Labels: enhancement

#42 Add filter to TimeLog viewset #40
  requirements/base.txt
  yumljira/apps/projects/admin.py
  yumljira/apps/projects/filters.py
  yumljira/apps/projects/serializers.py
  yumljira/apps/projects/tests.py
  yumljira/apps/projects/views.py
  yumljira/settings/base.py
Labels: enhancement

#44 Fix urls #43
  yumljira/apps/projects/urls.py
Labels: bug

#47 Add way to use string with period for time_logged parameter #46
  yumljira/apps/projects/choices.py
  yumljira/apps/projects/serializers.py
  yumljira/apps/projects/tests.py
Labels: enhancement

#50 Add comments #41
  yumljira/apps/projects/filters.py
  yumljira/apps/projects/migrations/0004_comment.py
  yumljira/apps/projects/models.py
  yumljira/apps/projects/serializers.py
  yumljira/apps/projects/test_factories.py
  yumljira/apps/projects/tests.py
  yumljira/apps/projects/urls.py
  yumljira/apps/projects/views.py
Labels: enhancement

#55 Refactor projects tests
  yumljira/apps/projects/serializers.py
  yumljira/apps/projects/tests.py
  yumljira/apps/projects/tests/__init__.py
  yumljira/apps/projects/tests/test_comment.py
  yumljira/apps/projects/tests/test_project.py
  yumljira/apps/projects/tests/test_tasks.py
  yumljira/apps/projects/tests/test_timelog_validation.py
  yumljira/apps/projects/tests/test_timelog_viewset.py
  yumljira/apps/projects/tests/utils.py
  yumljira/apps/projects/views.py
Labels: tests

#56 Add key field to Project model #49
  yumljira/apps/projects/migrations/0005_project_key.py
  yumljira/apps/projects/migrations/0006_auto_20190928_0646.py
  yumljira/apps/projects/models.py
  yumljira/apps/projects/serializers.py
  yumljira/apps/projects/test_factories.py
  yumljira/apps/projects/tests/test_project.py
Labels: bug

#51 Feature/login register
  client/App.vue
  client/router.js
  client/store/actions.js
  client/store/getters.js
  client/store/mutations.js
  client/store/state.js
  client/styles/custom.scss
  client/views/Login.vue
  client/views/MainPage.vue
  client/views/ProjectList.vue
  client/views/Register.vue
  package-lock.json
  yumljira/settings/auth.py
Labels: enhancement

#58 #30 #53 Add protect vue router urls
  client/router.js
Labels: enhancement
